//Vanilla
class HeadgearItem;
class Bag_Base;
class ItemInfo;
class H_HelmetB;
class B_Kitbag_cbr;
class B_Carryall_cbr;
class B_AssaultPack_cbr;
class UniformItem;
class HitPoints;
class HitHull;
class HitHRotor;
class B_Pilot_F;

//RHS Backpacks
class rhsusf_calonii_coy;
class rhsusf_falconii_coy;
class rhsusf_assault_eagleaiii_coy;
//ILBE
class tfw_ilbe_blade_coy;
class tfw_ilbe_blade_d;
class tfw_ilbe_blade_wd2;
class tfw_ilbe_blade_alpine;
class tfw_ilbe_whip_coy;
class tfw_ilbe_whipext_coy;
class tfw_ilbe_whip_alpine;
class tfw_ilbe_whipext_alpine;
class tfw_ilbe_whip_d;
class tfw_ilbe_whipext_d;
class tfw_ilbe_whip_wd2;
class tfw_ilbe_whipext_wd2;
class tfw_ilbe_DD_wd2;
class tfw_ilbe_DD_d;
class tfw_ilbe_DD_coy;
class tfw_ilbe_DD_alpine;
//Drones
class Toolkit;
class B_UAV_01_backpack_F;
class assembleInfo;
class ViewOptics;
class B_UAV_01_F;
class Turrets;
class MainTurret;
class B_rhsusf_B_BACKPACK;
//AirHelmets
class H_PilotHelmetFighter_B;
//InfantryHelmets
class rhsusf_ach_helmet_ucp_alt;
class rhsusf_ach_helmet_ESS_ucp_alt;
class rhsusf_ach_helmet_headset_ucp_alt;
class rhsusf_ach_helmet_headset_ess_ucp_alt;
class rhsusf_ach_helmet_ucp_norotos;
//Scopes
class rhsusf_acc_premier_mrds;
class Scot_Trij_Accu;
class Scot_Trij_Accu_RMR_Top_Canted;
class Scot_Trij_Accu_RMR;
class Scot_Trij_Accu_T1;
class Scot_Trij_Accu_T2;
class InventoryOpticsItem_Base_F;
class OpticsModes;
class ItemCore;
class asdg_OpticRail;
//RHS Helmets
class rhsusf_cvc_green_helmet;
class rhsusf_cvc_green_alt_helmet;
class rhsusf_cvc_green_ess;
class rhsusf_cvc_green_ess_helmet;
class rhsusf_cvc_helmet;
class rhsusf_cvc_alt_helmet;
class rhsusf_cvc_ess;
class rhsusf_cvc_ess_helmet;
class rhsusf_ach_helmet_camo_ocp;
class rhsusf_mich_bare_alt_semi;
class rhsusf_mich_bare_semi_headset;

//USP Helmets
class USP_OPSCORE_FASTMT_C;
class USP_OPS_FASTXP_CT_TAN;
class USP_OPSCORE_FASTMT_FCV;
class USP_OPSCORE_FASTMTC_M81_MGSW;
class USP_OPSCORE_FASTMTC_M81_MSW;
class USP_OPSCORE_FASTMTC_M81_CMGSW;
class USP_OPSCORE_FASTMTC_M81_CMSW;
class USP_OPSCORE_FASTMTC_M81_CGSW;
class USP_OPSCORE_FASTMTC_M81_CS;

//MOES Vests
class CMU33P;
class CMU33PTan;
class SV2B_LPU23P;
class SV2B_LPU36P;
class SRU21P;
class V_DeckCrew_blue_F;
class V_Safety_blue_F;
class SRU21P_LPU9P_PCU15AP_Alt;
class SRU21P_LPU9P_Alt;
class SRU21P_Alt;

//RHS Vests
class rhsusf_mbav;
class rhsusf_mbav_grenadier;
class rhsusf_mbav_light;
class rhsusf_mbav_mg;
class rhsusf_mbav_medic;
class rhsusf_mbav_rifleman;
class rhsusf_spc;
class rhsusf_spc_corpsman;
class rhsusf_spc_crewman;
class rhsusf_spc_iar;
class rhsusf_spc_light;
class rhsusf_spc_marksman;
class rhsusf_spc_rifleman;
class rhsusf_spc_sniper;
class rhsusf_spc_squadleader;
class rhsusf_spc_teamleader;
//Special Vests
class V_RebreatherB;
class V_DeckCrew_yellow_F;
class V_Safety_yellow_F;
class V_LegStrapBag_Coyote_F;
class V_LegStrapBag_black_F;
//MOES Uniforms
class CWU27P_Base;
class CWU27PTan_Base;
class CSU15BP_Base_Rolled_FG;
class CSU15BPTan_Base_Rolled_FG;
//RHS Uniforms
class rhs_uniform_FROG01_wd;
class rhs_uniform_FROG01_d;
class rhs_uniform_g3_rgr;
class rhs_uniform_g3_tan;
//Special Uniforms
class U_B_Wetsuit;
class U_C_CBRN_Suit_01_Wdl_F;
class Uniform_Base;
//Ammo
class BulletBase;
class BulletCore;
//Helmets
class rhsusf_opscore_mar_fg;
class rhsusf_opscore_mar_ut;
class rhsusf_opscore_mar_fg_pelt;
class rhsusf_opscore_mar_ut_pelt;
//Magazines
class 30Rnd_556x45_Stanag;
class rhs_mag_30Rnd_556x45_Mk262_PMAG;
class rhs_mag_30Rnd_556x45_Mk262_PMAG_Tan;
class rhs_mag_30Rnd_556x45_M855A1_PMAG;
class rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan;
class rhs_mag_30Rnd_556x45_Mk318_PMAG;
class rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan;
class rhs_mag_30Rnd_556x45_Mk318_SCAR;
class rhs_mag_30Rnd_556x45_Mk262_Stanag;
class rhs_mag_30Rnd_556x45_Mk318_Stanag;
class rhs_mag_30Rnd_556x45_M855A1_Stanag;
class rhs_mag_20Rnd_SCAR_762x51_m118_special;
class rhs_mag_20Rnd_SCAR_762x51_m118_special_bk;
class rhs_mag_20Rnd_SCAR_762x51_m61_ap;
class rhs_mag_20Rnd_SCAR_762x51_m61_ap_bk;
class rhs_mag_20Rnd_SCAR_762x51_m62_tracer;
class rhs_mag_20Rnd_SCAR_762x51_m62_tracer_bk;
class rhs_mag_20Rnd_SCAR_762x51_m80_ball;
class rhs_mag_20Rnd_SCAR_762x51_m80_ball_bk;
class rhs_mag_20Rnd_SCAR_762x51_m80a1_epr;
class rhs_mag_20Rnd_SCAR_762x51_m80a1_epr_bk;
class rhs_mag_20Rnd_SCAR_762x51_mk316_special;
class rhs_mag_20Rnd_SCAR_762x51_mk316_special_bk;

//Crye Vests
class USP_CRYE_CPC;
class USP_CRYE_CPC_COMMS;
class USP_CRYE_CPC_FAST_BELT;
class USP_CRYE_CPC_LEAD_BELT;
class USP_CRYE_CPC_LIGHT_BELT;
class USP_CRYE_CPC_MEDIC;
class USP_CRYE_CPC_WEAPON;
class USP_ZIPON_PANEL_CPC_CBR;
class USP_ZIPON_PANEL_CPC_BC_SM_CBR;
class USP_ZIPON_PANEL_CPC_SM_CBR;
class USP_DELTA_BAG_CBR;
class USP_REEBOW_3DAP_ACC7_CBR;
class USP_REEBOW_3DAP_ACC8_CBR;
class USP_VEST_STRANDHOGG2_CBR;
//Crye Backpacks
class USP_CRYE_BELT_PACK;
class USP_ZIPON_PANEL_CBR;
class USP_PACK_BREACHER_CBR;
class USP_PATROL_PACK_CBR;
class USP_HYDROPACK_CBR;
class USP_LAAW_CLIP;
class USP_REEBOW_3DAP_ACC9_CBR;
class USP_45L_RUCKSACK_TAN;
//USP Uniforms
class USP_G3C_M81;
class USP_G3F_G3C_MX_M81;
class USP_RUGBY_G3C_KP2_MX_RGR_M81;
class USP_SOFTSHELL_G3C_MX_RGR_M81;
class USP_TSHIRT2_G3C_MX_GRN_M81;
class USP_G3C_RS2_M81;
//ILBE Radio Backpacks
class tfw_ilbe_blade_wd;
//vanilla shit
class U_Tank_green_F;
//nightvision
class ACE_NVG_Gen4_Black_WP;
class rhsusf_ANPVS_15;

// Peral's USMC
class JPC_2_JTAC_Tan;
class JPC_2_Marksman_Tan;
class JPC_2_SL_Tan;