// Generated by tools/generate-sounds.py from tools/sound_lines.json - do not hand-edit.
class PTF_Sound_guardia_loyalty
{
	name = "PTF PA - Guardia: Loyalty Broadcast";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_loyalty.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_curfew
{
	name = "PTF PA - Guardia: Curfew Order";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_curfew.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_checkpoint
{
	name = "PTF PA - Guardia: Checkpoint Warning";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_checkpoint.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_reward
{
	name = "PTF PA - Guardia: Reward Offer";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_reward.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_weapons
{
	name = "PTF PA - Guardia: Weapons Amnesty";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_weapons.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_rations
{
	name = "PTF PA - Regime: Ration Notice";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_rations.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_evacuation
{
	name = "PTF PA - Regime: Evacuation Order";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_evacuation.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_victory
{
	name = "PTF PA - Regime: Victory Bulletin";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_victory.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_bastida_address
{
	name = "PTF PA - Bastida: Address to the Nation";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\bastida_address.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_sindicato_radio
{
	name = "PTF PA - Sindicato: Pirate Radio";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\sindicato_radio.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_sindicato_warning
{
	name = "PTF PA - Sindicato: Warning";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\sindicato_warning.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_hurricane
{
	name = "PTF PA - Regime: Hurricane Warning";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_hurricane.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_blackout
{
	name = "PTF PA - Regime: Power Rationing";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_blackout.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_boilwater
{
	name = "PTF PA - Regime: Water Advisory";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_boilwater.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_anthem_intro
{
	name = "PTF PA - Regime: Anthem Introduction";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_anthem_intro.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_pereno_recruitment
{
	name = "PTF PA - Perenos: Recruitment Ad";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\pereno_recruitment.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_sindicato_numbers
{
	name = "PTF PA - Sindicato: Numbers Game";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\sindicato_numbers.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_morning
{
	name = "PTF PA - Regime: Morning Bulletin";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_morning.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_martyrs
{
	name = "PTF PA - Regime: Martyrs Tribute";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_martyrs.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_regime_referendum
{
	name = "PTF PA - Regime: Referendum Appeal";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\regime_referendum.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_informants
{
	name = "PTF PA - Guardia: Report Strangers";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_informants.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_guardia_sindicato
{
	name = "PTF PA - Guardia: Anti-Sindicato Warning";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\guardia_sindicato.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_pereno_muster
{
	name = "PTF PA - Perenos: Battalion Muster";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\pereno_muster.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_sindicato_business
{
	name = "PTF PA - Sindicato: Open for Business";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\sindicato_business.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_anthem_valmera
{
	name = "PTF PA - Music: Himno de la Republica";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\anthem_valmera.ogg", 5.62, 1, 900};
	titles[] = {};
};
class PTF_Sound_march_guardia
{
	name = "PTF PA - Music: Marcha de la Guardia";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\march_guardia.ogg", 5.62, 1, 900};
	titles[] = {};
};
class PTF_Sound_radio_jingle
{
	name = "PTF PA - Radio Nacional: Station Ident";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\valmera\radio_jingle.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_son_valmera
{
	name = "PTF PA - Music: Son Valmerano";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\son_valmera.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_merengue_bocachico
{
	name = "PTF PA - Music: Merengue de Bocachico";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\merengue_bocachico.ogg", 5.62, 1, 700};
	titles[] = {};
};
class PTF_Sound_bolero_valmera
{
	name = "PTF PA - Music: Bolero (slow)";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\bolero_valmera.ogg", 5.62, 1, 600};
	titles[] = {};
};
class PTF_Sound_bells_church
{
	name = "PTF PA - Bells: Church";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\bells_church.ogg", 5.62, 1, 1000};
	titles[] = {};
};
class PTF_Sound_tone_attention
{
	name = "PTF PA - Tone: Attention Chime";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\tone_attention.ogg", 5.62, 1, 500};
	titles[] = {};
};
class PTF_Sound_siren_airraid
{
	name = "PTF PA - Siren: Air Raid";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\siren_airraid.ogg", 10, 1, 1800};
	titles[] = {};
};
class PTF_Sound_siren_twotone
{
	name = "PTF PA - Siren: Two-Tone Alert";
	sound[] = {"\z\PTF\addons\PTF_Sound\sounds\generic\siren_twotone.ogg", 10, 1, 1500};
	titles[] = {};
};
