class PTF_Factions_Cuba_Rifleman: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Rifleman";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    backpack="";
};
class PTF_Factions_Cuba_Grenadier: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Grenadier";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74_gp25",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74_gp25",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    backpack="";
};
class PTF_Factions_Cuba_Machinegunner: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Machinegunner";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_pkm",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_pkm",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_100Rnd_762x54mmR",
        "rhs_mag_9x18_8_57N181S",
        "rhs_100Rnd_762x54mmR",
        "rhs_100Rnd_762x54mmR",
        "rhs_100Rnd_762x54mmR"
    };
    respawnMagazines[]=
    {
        "rhs_100Rnd_762x54mmR",
        "rhs_mag_9x18_8_57N181S",
        "rhs_100Rnd_762x54mmR",
        "rhs_100Rnd_762x54mmR",
        "rhs_100Rnd_762x54mmR"
    };
    backpack="";
};
class PTF_Factions_Cuba_Squadlead: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Squad Leader";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom_khk",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom_khk",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74_gp25",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74_gp25",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_VOG25",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    backpack="rhs_r148";
};
class PTF_Factions_Cuba_AT: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Anti-Tank Rifleman";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "CUP_U_B_BDUv2_gloves_OD",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "CUP_U_B_BDUv2_gloves_OD",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm",
        "rhs_weap_rpg7"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm",
        "rhs_weap_rpg7"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag",
        "rhs_rpg7_PG7V_mag"
    };
    backpack="rhs_rpg_6b3";
};
class PTF_Factions_Cuba_Medic: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Medic";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "rhs_ssh60",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_rgn",
        "rhs_mag_rgn",
        "rhs_mag_rdg2_white",
        "rhs_mag_rdg2_white",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_30Rnd_545x39_7N6_AK"
    };
    backpack="rhs_medic_bag";
};
class PTF_Factions_Cuba_Sniper: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Sniper";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_ssh60",
        "rhs_chicom",
        "CUP_U_B_BDUv2_gloves_OD",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "CUP_U_B_BDUv2_gloves_OD",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_svds",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_svds",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_10Rnd_762x54mmR_7N1",
        "rhs_mag_9x18_8_57N181S",
        "rhs_10Rnd_762x54mmR_7N1",
        "rhs_mag_9x18_8_57N181S"
    };
    respawnMagazines[]=
    {
        "rhs_10Rnd_762x54mmR_7N1",
        "rhs_mag_9x18_8_57N181S",
        "rhs_10Rnd_762x54mmR_7N1",
        "rhs_mag_9x18_8_57N181S"
    };
    backpack="";
};
class PTF_Factions_Cuba_Officer: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Officer";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_ssh60",
        "rhs_chicom",
        "rhs_cossack_visor_cap_tan",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "rhs_cossack_visor_cap_tan",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S"
    };
    backpack="rhs_r148";
};
class PTF_Factions_Cuba_Crewman: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Crewman";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "rhs_tsh4",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "rhs_tsh4",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_aks74u",
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_aks74",
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S"
    };
    respawnMagazines[]=
    {
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S",
        "rhs_30Rnd_545x39_7N6_AK",
        "rhs_mag_9x18_8_57N181S"
    };
    backpack="";
};
class PTF_Factions_Cuba_Pilot: LOP_US_Infantry_SL
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Pilot";
    side=0;
    faction="PTF_Factions_Cuba";
    identityTypes[]=
    {
        "Head_TK",
        "LanguageRUS_F"
    };
    items[]=
    {
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_morphine",
        "ACE_tourniquet"
    };
    uniformClass="CUP_U_B_BDUv2_gloves_OD";
    linkedItems[]=
    {
        "rhs_chicom",
        "rhs_zsh7a_mike",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    respawnlinkedItems[]=
    {
        "rhs_chicom",
        "rhs_zsh7a_mike",
        "ItemMap",
        "rhs_radio_R169P1",
        "ItemCompass",
        "ItemWatch"
    };
    weapons[]=
    {
        "rhs_weap_makarov_pm"
    };
    respawnWeapons[]=
    {
        "rhs_weap_makarov_pm"
    };
    magazines[]=
    {
        "rhs_mag_9x18_8_57N181S",
        "rhs_mag_9x18_8_57N181S"
    };
    respawnMagazines[]=
    {
        "rhs_mag_9x18_8_57N181S",
        "rhs_mag_9x18_8_57N181S"
    };
    backpack="rhs_r148";
};
class PTF_Factions_Cuba_KORD6T7: rhs_KORD_MSV
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="KORD (6T7)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_KORD6U16: rhs_KORD_high_MSV
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="KORD  (6U16)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_NSV6T7: RHS_NSV_TriPod_MSV
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="NSV (6T7)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_SPG9M: rhs_SPG9M_MSV
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="SPG-9M";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_Kornet: rhs_Kornet_9M133_2_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="9K133-1 'Kornet-M'";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_BTR60PB: rhs_btr60_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BTR-60PB";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BTR70: rhs_btr70_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BTR-70";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BTR80: rhs_btr80_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BTR-80";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_Podnos: rhs_2b14_82mm_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Podnos";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman",
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_2A18MD30A: rhs_D30_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="2A18M (D-30A)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman",
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_UAZ: RHS_UAZ_MSV_01
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="UAZ-3151";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_BMP1: rhs_bmp1_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMP-1";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BMP1P: rhs_bmp1p_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMP-1P";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BMP1K: rhs_bmp1k_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMP-1K";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BMP1D: rhs_bmp1d_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMP-1D";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BRDM2: rhsgref_BRDM2_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BRDM-2";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BRDM2UM: rhsgref_BRDM2_HQ_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BRDM-2UM";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_GAZ66: rhs_gaz66_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_Flatbed: rhs_gaz66_flat_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 (Flatbed)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_R142N: rhs_gaz66_r142_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 (R-142N)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_ESB8IM: rhs_gaz66_repair_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 ESB-8IM";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_AP2: rhs_gaz66_ap2_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 AP-2";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_Ammo: rhs_gaz66_ammo_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 (Ammo)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
};
class PTF_Factions_Cuba_GAZ66_ZU23: rhs_gaz66_zu23_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="GAZ-66 (ZU-23-2)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Rifleman",
        "PTF_Factions_Cuba_Rifleman",
        "PTF_Factions_Cuba_Rifleman"
    };
};
class PTF_Factions_Cuba_Mi24P: RHS_Mi24P_vdv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Mi-24P";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Pilot";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Pilot",
        "PTF_Factions_Cuba_Pilot"
    };
};
class PTF_Factions_Cuba_Mi8_MT: RHS_Mi8mt_vdv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Mi-8MT";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Pilot";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Pilot",
        "PTF_Factions_Cuba_Pilot",
        "PTF_Factions_Cuba_Pilot"
    };
};
class PTF_Factions_Cuba_Mi8_MTV: RHS_Mi8MTV3_heavy_vdv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Mi-8MTV-3 (Heavy)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Pilot";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Pilot",
        "PTF_Factions_Cuba_Pilot",
        "PTF_Factions_Cuba_Pilot"
    };
};
class PTF_Factions_Cuba_Mig29S: rhs_mig29s_vmf
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="Mig-29S";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Pilot";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Pilot"
    };
};
class PTF_Factions_Cuba_2S1: rhs_2s1_tv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="2S1";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_2S3M1: rhs_2s3_tv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="2S3M1";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_T72B: rhs_t72ba_tv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="T-72B";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_ZSU23: rhs_zsu234_aa
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="ZSU-23-4V";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BM21: RHS_BM21_VDV_01
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BM-21";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_PTSM: rhs_pts_vmf
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="PTS-M";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_PRP: rhs_prp3_vv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="PRP-3";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BMK: rhs_bmk_t
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMK Tug";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BRM: rhs_brm1k_vmf
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BRM-1K";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_BDM1: rhs_bmd1
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="BMD-1";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Crewman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};
class PTF_Factions_Cuba_9K38: rhs_Igla_AA_pod_msv
{
    author="Paramarine Task Force";
    scope=2;
    scopeCurator=2;
    displayName="9K38 (Djigit)";
    side=0;
    faction="PTF_Factions_Cuba";
    crew="PTF_Factions_Cuba_Rifleman";
    typicalCargo[]=
    {
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman",
        "PTF_Factions_Cuba_Crewman"
    };
};