["Empty", [[],[],[],[],[],[],"","",[],["","","","","",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["Service Dress - Enlisted", [[],[],[],["U_US_class_A_ab_inf_enlisted",[]],[],[],"PTF_Helmet_Service_Cap","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["Rifleman", [["rhs_weap_m27iar_grip","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_USMC",[],[],""],[],["CUP_hgun_M17_Black","","","",["CUP_21Rnd_9x19_M17_Black",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_CableTie",2],["ACE_EarPlugs",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_salineIV_250",1],["ACE_tourniquet",1]]],["PTF_Vest_Infantry_CRYE_Fast",[["ACE_fieldDressing",5],["ACE_quikclot",5],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_tourniquet",2],["ACE_WaterBottle",1],["PTF_Mag_556x45_Mk262_PMAG_Mix",10,30],["CUP_21Rnd_9x19_M17_Black",3,21],["rhs_mag_m67",5,1],["ACE_CTS9",3,1],["SmokeShell",4,1]]],["PTF_Backpack_Infantry_Falcon",[["ACE_bodyBag",2],["ACE_IR_Strobe_Item",1],["PTF_Mag_556x45_Mk318_PMAG_Mix",5,30],["CUP_21Rnd_9x19_M17_Black",2,21],["ACE_CTS9",2,1],["rhs_mag_m67",3,1],["SmokeShell",4,1]]],"PTF_Helmet_Infantry_Mich2000_WD","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_272","ItemCompass","ACE_Altimeter",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["Grenadier", [["rhs_weap_m4a1_carryhandle_m203","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_USMC",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],["CUP_hgun_M17_Black","","","",["CUP_21Rnd_9x19_M17_Black",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_CableTie",2],["ACE_EarPlugs",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_salineIV_250",1],["ACE_tourniquet",1]]],["PTF_Vest_Infantry_CRYE_Fast",[["ACE_fieldDressing",5],["ACE_quikclot",5],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_tourniquet",2],["ACE_WaterBottle",1],["PTF_Mag_556x45_Mk262_PMAG_Mix",10,30],["CUP_21Rnd_9x19_M17_Black",3,21],["rhs_mag_m67",5,1],["ACE_CTS9",3,1],["SmokeShell",4,1]]],["PTF_Backpack_Infantry_Falcon",[["ACE_bodyBag",2],["ACE_IR_Strobe_Item",1],["PTF_Mag_556x45_Mk318_PMAG_Mix",5,30],["CUP_21Rnd_9x19_M17_Black",2,21],["ACE_CTS9",2,1],["rhs_mag_m67",4,1],["SmokeShell",4,1],["rhs_mag_M397_HET",10,1],["rhs_mag_M433_HEDP",10,1],["rhs_mag_m714_White",5,1],["UGL_FlareWhite_F",2,1],["ACE_40mm_Flare_white",2,1],["rhs_mag_m713_Red",2,1],["rhs_mag_m715_Green",2,1]]],"PTF_Helmet_Infantry_Mich2000_WD","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_272","ItemCompass","ACE_Altimeter",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Automatic Rifleman", [["rhs_weap_m249_pip_L_para","rhsusf_acc_SFMB556","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_USMC",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["CUP_hgun_M17_Black","","","",["CUP_21Rnd_9x19_M17_Black",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_CableTie",2],["ACE_EarPlugs",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_salineIV_250",1],["ACE_tourniquet",1]]],["PTF_Vest_Infantry_CRYE_Fast",[["ACE_fieldDressing",5],["ACE_quikclot",5],["ACE_EntrenchingTool",1],["ACE_salineIV_500",1],["ACE_tourniquet",2],["ACE_WaterBottle",1],["CUP_21Rnd_9x19_M17_Black",3,21],["rhs_mag_m67",5,1],["ACE_CTS9",3,1],["SmokeShell",4,1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",2,200]]],["PTF_Backpack_Infantry_Falcon",[["ACE_bodyBag",2],["ACE_IR_Strobe_Item",1],["CUP_21Rnd_9x19_M17_Black",2,21],["ACE_CTS9",2,1],["rhs_mag_m67",4,1],["SmokeShell",4,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_ucp",2,100],["rhsusf_200Rnd_556x45_mixed_soft_pouch",3,200],["PTF_Mag_556x45_Mk318_PMAG_Mix",2,30]]],"PTF_Helmet_Infantry_Mich2000_WD","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_272","ItemCompass","ACE_Altimeter",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["MAG Pilot", [[],[],[],["PTF_Uniform_Air_CSU15BP_D",[]],["PTF_Vest_Air_CMU33P_D",[]],["PTF_Backpack_Air_Carryall_Invis",[["PTF_Helmet_Air_Black",1]]],"r_Garrison_cap_AB_inf_2LT","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["MAG SNA", [[],[],[],["PTF_Uniform_Air_SNA_USN",[]],["PTF_Vest_Air_SRU21P",[]],["PTF_Backpack_Air_Carryall_Invis",[["PTF_Helmet_Air_Black",1]]],"r_Garrison_cap_AB_inf_2LT","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]] call ace_arsenal_fnc_addDefaultLoadout;