["Empty", [[],[],[],[],[],[],"","",[],["","","","","",""]]] call ace_arsenal_fnc_addDefaultLoadout;

["Assistant Squad Leader D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Assistant Squad Leader S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Assistant Squad Leader WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Breacher D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["tsp_breach_popper_mag",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhsusf_5Rnd_Slug",5,5],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Breacher S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["tsp_breach_popper_mag",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhsusf_5Rnd_Slug",5,5],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Breacher WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["tsp_breach_popper_mag",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhsusf_5Rnd_Slug",5,5],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Combat Engineer D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["DemoCharge_Remote_Mag",4,1],["tsp_breach_popper_mag",4,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",2,1],["rhs_mag_m67",2,1],["ACE_CTS9",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["ace_marker_flags_orange",20],["ace_marker_flags_red",10],["ace_marker_flags_yellow",20],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Combat Engineer S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["DemoCharge_Remote_Mag",4,1],["tsp_breach_popper_mag",4,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",2,1],["rhs_mag_m67",2,1],["ACE_CTS9",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["ace_marker_flags_orange",20],["ace_marker_flags_red",10],["ace_marker_flags_yellow",20],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Combat Engineer WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,4]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Chemlight_IR",2,1],["tsp_breach_block_mag",3,1],["DemoCharge_Remote_Mag",4,1],["tsp_breach_popper_mag",4,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",2,1],["rhs_mag_m67",2,1],["ACE_CTS9",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["ace_marker_flags_orange",20],["ace_marker_flags_red",10],["ace_marker_flags_yellow",20],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],[["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_Slug",5],[],""],1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Corpsman D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",8],["ACE_fieldDressing",10],["ACE_quikclot",10],["ACE_splint",8],["ACE_packingBandage",15],["ACE_elasticBandage",15],["kat_Painkiller",8,4]]],["PTF_Vest_Infantry_CRYE",[["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["kat_IV_16",15],["kat_AED",1],["kat_EACA",10],["kat_naloxone",5],["kat_nitroglycerin",5],["kat_norepinephrine",5],["kat_TXA",10],["kat_IO_FAST",15],["ItemcTab",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellPurple",2,1],["kat_Carbonate",5,10]]],["PTF_Backpack_Infantry_Corpsman_Kitbag_Black",[["ACE_plasmaIV_500",6],["ACE_plasmaIV_250",3],["ACE_plasmaIV",8],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Corpsman S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",8],["ACE_fieldDressing",10],["ACE_quikclot",10],["ACE_splint",8],["ACE_packingBandage",15],["ACE_elasticBandage",15],["kat_Painkiller",8,4]]],["PTF_Vest_Infantry_CRYE",[["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["kat_IV_16",15],["kat_AED",1],["kat_EACA",10],["kat_naloxone",5],["kat_nitroglycerin",5],["kat_norepinephrine",5],["kat_TXA",10],["kat_IO_FAST",15],["ItemcTab",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellPurple",2,1],["kat_Carbonate",5,10]]],["PTF_Backpack_Infantry_Corpsman_Kitbag_Black",[["ACE_plasmaIV_500",6],["ACE_plasmaIV_250",3],["ACE_plasmaIV",8],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Corpsman WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",8],["ACE_fieldDressing",10],["ACE_quikclot",10],["ACE_splint",8],["ACE_packingBandage",15],["ACE_elasticBandage",15],["kat_Painkiller",8,4]]],["PTF_Vest_Infantry_CRYE",[["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["kat_IV_16",15],["kat_AED",1],["kat_EACA",10],["kat_naloxone",5],["kat_nitroglycerin",5],["kat_norepinephrine",5],["kat_TXA",10],["kat_IO_FAST",15],["ItemcTab",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellPurple",2,1],["kat_Carbonate",5,10]]],["PTF_Backpack_Infantry_Corpsman_Kitbag_Black",[["ACE_plasmaIV_500",6],["ACE_plasmaIV_250",3],["ACE_plasmaIV",8],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Crewman D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_G3_Tan",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ToolKit",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"rhsusf_cvc_alt_helmet","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Crewman WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_G3_Green",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ToolKit",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"rhsusf_cvc_green_alt_helmet","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Automatic Rifleman D",[[["rhs_weap_m249_light_S","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",6,200]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Automatic Rifleman S",[[["rhs_weap_m249_light_S","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",6,200]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Automatic Rifleman WD",[[["rhs_weap_m249_light_S","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",6,200]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Marksman D",[[["rhs_weap_sr25","","rhsusf_acc_anpeq16a","PTF_Infantry_Weapon_Scope_M8541A",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_20Rnd_762x51_SR25_m993_Mag",9,20],["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",1,20],["rhsusf_20Rnd_762x51_SR25_m62_Mag",1,20]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Marksman S",[[["rhs_weap_sr25","","rhsusf_acc_anpeq16a","PTF_Infantry_Weapon_Scope_M8541A",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_20Rnd_762x51_SR25_m993_Mag",9,20],["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",1,20],["rhsusf_20Rnd_762x51_SR25_m62_Mag",1,20]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Designated Marksman WD",[[["rhs_weap_sr25","","rhsusf_acc_anpeq16a","PTF_Infantry_Weapon_Scope_M8541A",["rhsusf_20Rnd_762x51_SR25_m993_Mag",20],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhsusf_20Rnd_762x51_SR25_m993_Mag",9,20],["rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",1,20],["rhsusf_20Rnd_762x51_SR25_m62_Mag",1,20]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Fireteam Leader D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Fireteam Leader S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Fireteam Leader WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Grenadier D",[[["rhs_weap_m16a4_imod_M203","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],["rhs_mag_M441_HE",1],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhs_mag_M441_HE",9,1],["1Rnd_Smoke_Grenade_shell",8,1],["rhs_mag_M433_HEDP",5,1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Grenadier S",[[["rhs_weap_m16a4_imod_M203","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],["rhs_mag_M441_HE",1],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhs_mag_M441_HE",9,1],["1Rnd_Smoke_Grenade_shell",8,1],["rhs_mag_M433_HEDP",5,1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Grenadier WD",[[["rhs_weap_m16a4_imod_M203","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],["rhs_mag_M441_HE",1],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["rhs_mag_M441_HE",9,1],["1Rnd_Smoke_Grenade_shell",8,1],["rhs_mag_M433_HEDP",5,1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Heavy Anti-Tank D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["launch_MRAWS_sand_F","","","",["MRAWS_HE_F",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["MRAWS_HE_F",3,1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Heavy Anti-Tank S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["launch_MRAWS_olive_F","","","",["MRAWS_HE_F",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["MRAWS_HE_F",3,1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Heavy Anti-Tank WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["launch_MRAWS_olive_F","","","",["MRAWS_HE_F",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30],["MRAWS_HE_F",3,1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Javelin Operator D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fgm148","","","",["rhs_fgm148_magazine_AT",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fgm148_magazine_AT",1,1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Javelin Operator S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fgm148","","","",["rhs_fgm148_magazine_AT",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fgm148_magazine_AT",1,1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Javelin Operator WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fgm148","","","",["rhs_fgm148_magazine_AT",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fgm148_magazine_AT",1,1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Joint Terminal Attack Controller D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["tfw_rf3080Item",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellBlue",10,1],["SmokeShellPurple",1,1],["SmokeShellRed",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Joint Terminal Attack Controller S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["tfw_rf3080Item",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellBlue",10,1],["SmokeShellPurple",1,1],["SmokeShellRed",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Joint Terminal Attack Controller WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["tfw_rf3080Item",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["SmokeShellBlue",10,1],["SmokeShellPurple",1,1],["SmokeShellRed",5,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Machine Gunner D",[[["rhs_weap_m240B","","","rhsusf_acc_ACOG_MDO",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Tripod",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["rhsusf_100Rnd_762x51_m80a1epr",3,100]]],["PTF_Backpack_Infantry_Assault",[["rhsusf_100Rnd_762x51_m80a1epr",9,100]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Machine Gunner S",[[["rhs_weap_m240B","","","rhsusf_acc_ACOG_MDO",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Tripod",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["rhsusf_100Rnd_762x51_m80a1epr",3,100]]],["PTF_Backpack_Infantry_Assault",[["rhsusf_100Rnd_762x51_m80a1epr",9,100]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Machine Gunner WD",[[["rhs_weap_m240B","","","rhsusf_acc_ACOG_MDO",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_Tripod",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["rhsusf_100Rnd_762x51_m80a1epr",3,100]]],["PTF_Backpack_Infantry_Assault",[["rhsusf_100Rnd_762x51_m80a1epr",9,100]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["PRT",[[["rhs_weap_m16a4_carryhandle","","","",[],[],""],[],[],["PTF_Uniform_Infantry_FROG_WD",[["ACE_EarPlugs",1],["ACE_fieldDressing",1],["ACE_quikclot",1],["ACE_tourniquet",1],["ACE_splint",1],["kat_Painkiller",1,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1]]],[],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Rifleman D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Rifleman S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Rifleman WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_M136","","","",[],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Service Alphas",[[[],[],[],["U_US_class_A_ab_inf_enlisted",[]],[],[],"r_Garrison_cap_AB_inf_2LT","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Squad Leader D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Squad Leader S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Squad Leader WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],[],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Stinger Operator D",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_D",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fim92_mag",2,1]]],"PTF_Helmet_Infantry_Mich2000_D","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Stinger Operator S",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_S",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fim92_mag",2,1]]],"PTF_Helmet_Infantry_Mich2000_S","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;

["Stinger Operator WD",[[["rhs_weap_m16a4_imod","","rhsusf_acc_anpeq16a","rhsusf_acc_ACOG_RMR",["PTF_Mag_556x45_Mk262_Stanag_Mix",30],[],""],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],["MHS_M18","","","",["MHS_21rnd_9MM_124FMJ_M17",21],[],""],["PTF_Uniform_Infantry_FROG_WD",[["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",15],["ACE_splint",2],["kat_Painkiller",3,10]]],["PTF_Vest_Infantry_CRYE",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_CableTie",3],["ACE_IR_Strobe_Item",1],["PTF_Nightvision_PVS15_WP",1],["ACE_EntrenchingTool",1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_IR",2,1],["PTF_Mag_556x45_Mk262_Stanag_Mix",14,30]]],["PTF_Backpack_Infantry_Assault",[["ACE_plasmaIV_500",1],["rhs_fim92_mag",2,1]]],"PTF_Helmet_Infantry_Mich2000_WD","",["ACE_Vector","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]],[["ace_earplugs",true]]]] call ace_arsenal_fnc_addDefaultLoadout;
